version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: "chore(deps/actions)"
    labels:
      - dependencies
      - github-actions
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: "chore(deps/go)"
    labels:
      - dependencies
      - go
    groups:
      go-modules:
        patterns:
          - "*"
